language: node_js

node_js:
  - 'node'
  - 'lts/*'

cache:
  directories:
    - 'node_modules'

script:
  - npm install
  - npm run prettier:check

deploy:
  provider: script
  script: npm run deploy
  on:
    branch: master
