language: node_js

node_js:
  - 'node'
  - 'lts/*'

matrix:
  include:
    - node_js: 'node'
    - node_js: 'lts/*'

cache:
  directories:
    - 'node_modules'

script:
  - npm run prettier:check

jobs:
  include:
    - stage: deploy
      if: branch = master
      node_js: 'node'
      script:
        - echo 'Configuring git and updating post dates...'
        - git config --global user.email "contact@travis-ci.com"
        - git config --global user.name "Travis CI"
        - echo 'Deploying to now ...'
        - npm install -g now
        - now --prod --token ${NOW_TOKEN}
